### ISSUE TITLE
Allow users to specify qunitjs version

### ISSUE THREAD

**Issue by Krinkle** [kof/node-qunit#117] opened 2015-03-13 01:30 UTC
Under npm 1.x it loads qunitjs 1.10.0 which is quite old at this point.

Projects like karma-qunit specify a minimum version, thus allowing the final consumer to specify a different version in their package.json. https://github.com/karma-runner/karma-qunit/blob/v0.1.4/package.json:
```json
  "peerDependencies": {
    "qunitjs": "^1.14.0"
  },
```

Under npm 2.x it interestingly refuses to load 1.10.0 alongside a newer version in some cases, resutling in the following:
```
npm WARN unmet dependency qunit requires qunitjs@'1.10.0' but will load qunitjs, which is version 1.17.1
```

.. on a project with:
```json
  "devDependencies": {
    "karma": "0.12.31",
    "karma-qunit": "0.1.4",
    "qunit": "0.7.5",
    "qunitjs": "1.17.1"
```

**Comment by nikolas** [comment] 2015-04-10 18:39
Thanks for looking into this. This is kind of a duplicate of issue #110

**Comment by jzaefferer** [comment] 2015-10-28 14:30
Closing as duplicate of #110.

**Closed by jzaefferer** 2015-10-28 14:30 UTC
